### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rsoorajs** [sachinOraon/Torrent-Leecher#1]
not working..if we added a magnetic url,it always stucks at saying "Getting file info"

i tried several urls and getting the same error

**Comment by telegrambotdev** [comment]
i tried several  times and not yet working

**Comment by telegrambotdev** [comment]
![Screenshot_2020-07-06-13-07-36-15](https://user-images.githubusercontent.com/20116017/86621607-1557b000-bfdc-11ea-821a-8e3c503b9d78.png)



keep showing this
