### ISSUE TITLE
need archive feature 

### ISSUE THREAD

**Issue by telegrambotdev** [sachinOraon/Torrent-Leecher#2]
can you add zipping feature too ? 
like if there is a 100 files in a torrent,thats so hard to download one by one.

so if you add an archive feature that will be very useful

**Comment by sachinOraon** [comment]
`h5ai` already has archiving feature. It lets you select the files and download them as a archive. You can change the format of archive in this file `files/_h5ai/private/conf/options.json` at line 127. The archive type can be `php-tar`, `shell-tar`, or `shell-zip`.
