### ISSUE TITLE
TORRENT DOWNLOAD NEVER STARTS

### ISSUE THREAD

**Issue by telegrambotdev** [sachinOraon/Torrent-Leecher#3]
Torrent leeching are always stay stucks at showing `Getting File Info`

no progress or nothing is showing.also how can i delete downloaded file.when i click download torrent file,it asks for password.which password ?

also if we type a word and click download,it still shows 'Getting file info`

can you fix all these bugs ?

![IMG_20200726_221431_381](https://user-images.githubusercontent.com/20116017/88484714-40f00980-cf8e-11ea-9e12-62d7d4e554eb.jpg)

**Comment by sachinOraon** [comment]
First of all, thanks a lot for giving it a try. I'm sorry for not able to comment earlier.
Q> When i click download torrent file, it asks for password. which password ?
A> Open getInfo.php file. At line 3 you will find the `$pass` variable.
Q> Torrent leeching are always stay stucks at showing `Getting File Info`.
A> For torrents with less seeds, the python script takes some time to download metadata, till then it shows that. However, once it gets the metadata, it shows the download percentage like this. Do you know any other torrent downloading script that is not using `pyhton-libtorrent` library as I feel like it's very slow. Kindly let me know.
![Capture](https://user-images.githubusercontent.com/22697903/88610528-869ef600-d0a4-11ea-8591-95afe131196e.JPG)
Q> If we type a word and click download, it still shows 'Getting file info`.
A> Yeah, currently there are no filters that will check for the validity of submitted link. However invalid link will start the process but eventually it will stop after 5 minutes.
